# Generated by Django 3.1.7 on 2021-07-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='calidad',
            new_name='categoria',
        ),
    ]
