# Generated by Django 3.1.7 on 2021-07-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_auto_20210702_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='calidad',
        ),
    ]
