# Generated by Django 3.1.7 on 2021-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_auto_20210702_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='calidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='calidad',
            field=models.ManyToManyField(to='local.Calidad'),
        ),
    ]
