# Generated by Django 3.1.7 on 2021-07-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_auto_20210702_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='calidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='calidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='local.calidad'),
            preserve_default=False,
        ),
    ]
